"""Create lute_terms table

Revision ID: dc0e9f6a0252
Revises: 
Create Date: 2024-09-21 10:07:52.761058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0e9f6a0252'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lute_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('translation', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('link_status', sa.String(), nullable=True),
    sa.Column('pronunciation', sa.String(), nullable=True),
    sa.Column('anki_note_id', sa.Integer(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lute_terms')
    # ### end Alembic commands ###
