"""adds new table

Revision ID: e35188dd85ba
Revises: eb21fba039fd
Create Date: 2024-10-05 12:57:33.276458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35188dd85ba'
down_revision: Union[str, None] = 'eb21fba039fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_declensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lute_entry_id', sa.Integer(), nullable=True),
    sa.Column('singular_definite', sa.String(), nullable=True),
    sa.Column('plural_indefinite', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lute_entry_id'], ['lute_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lute_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name_declensions')
    # ### end Alembic commands ###
